-- AlterTable
ALTER TABLE `new_orders` MODIFY `qty` BIGINT NOT NULL,
MODIFY `remains` BIGINT NOT NULL DEFAULT 0,
MODIFY `startCount` BIGINT NOT NULL DEFAULT 0,
MODIFY `maxQty` BIGINT NULL,
MODIFY `minQty` BIGINT NULL;

