import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

async function seedServiceTypes() {
  console.log('Seeding service types...')

  const serviceTypes = [
    {
      name: 'Default',
      description: 'Standard service requiring link and quantity',
      status: 'active',
      packageType: 1,
      requiresLink: true,
      requiresQuantity: true,
      requiresComments: false,
      requiresUsername: false,
      requiresPosts: false,
      requiresDelay: false,
      requiresMin: false,
      requiresMax: false,
      supportsDripfeed: true,
      supportsRefill: true,
      supportsCancel: true,
      isSubscription: false,
      isAutoService: false,
    },
    {
      name: 'Package',
      description: 'Package service with custom quantity handling',
      status: 'active',
      packageType: 2,
      requiresLink: true,
      requiresQuantity: true,
      requiresComments: false,
      requiresUsername: false,
      requiresPosts: false,
      requiresDelay: false,
      requiresMin: false,
      requiresMax: false,
      supportsDripfeed: true,
      supportsRefill: true,
      supportsCancel: true,
      isSubscription: false,
      isAutoService: false,
    },
    {
      name: 'Special Comments',
      description: 'Service requiring custom comments',
      status: 'active',
      packageType: 3,
      requiresLink: true,
      requiresQuantity: true,
      requiresComments: true,
      requiresUsername: false,
      requiresPosts: false,
      requiresDelay: false,
      requiresMin: false,
      requiresMax: false,
      supportsDripfeed: true,
      supportsRefill: true,
      supportsCancel: true,
      isSubscription: false,
      isAutoService: false,
    },
    {
      name: 'Package Comments',
      description: 'Package service with comments support',
      status: 'active',
      packageType: 4,
      requiresLink: true,
      requiresQuantity: true,
      requiresComments: true,
      requiresUsername: false,
      requiresPosts: false,
      requiresDelay: false,
      requiresMin: false,
      requiresMax: false,
      supportsDripfeed: true,
      supportsRefill: true,
      supportsCancel: true,
      isSubscription: false,
      isAutoService: false,
    },
    {
      name: 'Auto Likes',
      description: 'Automatic likes service',
      status: 'active',
      packageType: 11,
      requiresLink: true,
      requiresQuantity: false,
      requiresComments: false,
      requiresUsername: true,
      requiresPosts: true,
      requiresDelay: true,
      requiresMin: true,
      requiresMax: true,
      supportsDripfeed: false,
      supportsRefill: false,
      supportsCancel: true,
      isSubscription: false,
      isAutoService: true,
    },
    {
      name: 'Auto Views',
      description: 'Automatic views service',
      status: 'active',
      packageType: 12,
      requiresLink: true,
      requiresQuantity: false,
      requiresComments: false,
      requiresUsername: true,
      requiresPosts: true,
      requiresDelay: true,
      requiresMin: true,
      requiresMax: true,
      supportsDripfeed: false,
      supportsRefill: false,
      supportsCancel: true,
      isSubscription: false,
      isAutoService: true,
    },
    {
      name: 'Auto Comments',
      description: 'Automatic comments service',
      status: 'active',
      packageType: 13,
      requiresLink: true,
      requiresQuantity: false,
      requiresComments: true,
      requiresUsername: true,
      requiresPosts: true,
      requiresDelay: true,
      requiresMin: true,
      requiresMax: true,
      supportsDripfeed: false,
      supportsRefill: false,
      supportsCancel: true,
      isSubscription: false,
      isAutoService: true,
    },
    {
      name: 'Subscription',
      description: 'Subscription-based service',
      status: 'active',
      packageType: 14,
      requiresLink: true,
      requiresQuantity: false,
      requiresComments: false,
      requiresUsername: false,
      requiresPosts: false,
      requiresDelay: true,
      requiresMin: true,
      requiresMax: true,
      supportsDripfeed: false,
      supportsRefill: false,
      supportsCancel: true,
      isSubscription: true,
      isAutoService: false,
    },
    {
      name: 'Limited Auto Likes',
      description: 'Limited automatic likes service',
      status: 'active',
      packageType: 15,
      requiresLink: true,
      requiresQuantity: false,
      requiresComments: false,
      requiresUsername: true,
      requiresPosts: true,
      requiresDelay: true,
      requiresMin: true,
      requiresMax: true,
      supportsDripfeed: false,
      supportsRefill: false,
      supportsCancel: true,
      isSubscription: false,
      isAutoService: true,
      maxQuantity: 10000,
      minQuantity: 100,
    },
  ]

  for (const serviceType of serviceTypes) {
    await prisma.serviceTypes.upsert({
      where: { name: serviceType.name },
      update: serviceType,
      create: serviceType,
    })
  }

  console.log('Service types seeded successfully!')
}

async function main() {
  try {
    await seedServiceTypes()
  } catch (error) {
    console.error('Error seeding service types:', error)
    process.exit(1)
  } finally {
    await prisma.$disconnect()
  }
}

main()